version: '3.8'

services:
  project:
    container_name: app
    build: .
    ports:
      - "5555:5555"
    environment:
      database: localarray
    networks:
      - app-net

networks:
  app-net: